import test from 'node:test';import assert from 'node:assert/strict';import {validatePurchaseFinance,paymentLabel,type Purchase} from '../src/lib/material-purchases';
const item:Purchase={id:'a',name:'Wood',quantity:1,unit:'each',totalCents:10000,vendor:'Vendor',date:'2026-10-04',phase:'Framing',location:'Garage',status:'received'};
test('receipt does not imply payment; unknown values stay unknown',()=>{assert.equal(paymentLabel(item),'Não informado');assert.equal(paymentLabel({...item,paidCents:0}),'Não pago');assert.equal(paymentLabel({...item,paidCents:5000}),'Parcialmente pago');assert.equal(paymentLabel({...item,status:'ordered',paidCents:10000}),'Pago');validatePurchaseFinance(item);validatePurchaseFinance({...item,taxCents:500,paidCents:10000});assert.equal(item.totalCents,10000);});
test('financial fields reject overpayments, invalid taxes and dates',()=>{for(const patch of [{paidCents:10001},{taxCents:-1},{taxCents:10001},{paidCents:0.5},{dueDate:'2026-02-30'},{status:'planned',paidCents:10}])assert.throws(()=>validatePurchaseFinance({...item,...patch}));});

import {calculatePurchaseTotal,inputCents} from '../src/lib/material-purchases';
test('quantity times unit price plus tax and shipping, with cent rounding',()=>{assert.equal(calculatePurchaseTotal(3,1000,250,500),3750);assert.equal(calculatePurchaseTotal(1.5,999,0,0),1499);assert.equal(inputCents('10.29'),1029);assert.throws(()=>inputCents('1.001'));assert.throws(()=>calculatePurchaseTotal(1,100,0,-1));assert.throws(()=>validatePurchaseFinance({...item,quantity:3,unitCostCents:1000,taxCents:250,shippingCents:500,totalCents:3000}));validatePurchaseFinance({...item,quantity:3,unitCostCents:1000,taxCents:250,shippingCents:500,totalCents:3750});});

import {calculateSalesTax} from '../src/lib/material-purchases';
test('sales tax uses explicit shipping basis and cent rounding',()=>{assert.equal(calculateSalesTax(10000,1000,7.25,false),725);assert.equal(calculateSalesTax(10000,1000,7.25,true),798);assert.equal(calculateSalesTax(10000,1000,0,true),0);assert.throws(()=>calculateSalesTax(100,0,-1,false));assert.throws(()=>calculateSalesTax(100,0,7.12345,false));assert.throws(()=>validatePurchaseFinance({...item,unitCostCents:10000,shippingCents:1000,taxCents:725,taxMode:'rate',taxRate:7.25,shippingTaxable:true,totalCents:11725}));});
