"use client";
import Link from 'next/link';import {useEffect,useState} from 'react';
import {KitchenScene} from './kitchen-scene';
import {elements,PILOT_KEY,readPilot,completedPilot,simulatedPilot,type PilotEvent,type ElementId} from '@/lib/kitchen-pilot';
import {readPlan,PLAN_KEY,schedulePlan,type ScheduledTask} from '@/lib/planning';
export function KitchenPilot(){
 const [events,setEvents]=useState<PilotEvent[]>([]),[tasks,setTasks]=useState<ScheduledTask[]>([]),[mode,setMode]=useState<'actual'|'simulation'>('actual'),[date,setDate]=useState('2026-10-05'),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[xray,setXray]=useState(false);
 useEffect(()=>{const load=()=>{try{setEvents(readPilot(localStorage.getItem(PILOT_KEY)));setTasks(schedulePlan(readPlan(localStorage.getItem(PLAN_KEY))));setReady(true);setError('');}catch(e){setReady(false);setError(e instanceof Error?e.message:'Falha ao abrir o piloto.');}};load();const listener=(e:StorageEvent)=>{if(e.key===PILOT_KEY||e.key===PLAN_KEY||e.key===null)load();};window.addEventListener('storage',listener);return()=>window.removeEventListener('storage',listener);},[]);
 const actual=completedPilot(events),shown=mode==='actual'?actual:simulatedPilot(tasks,date);
 async function record(element:ElementId,done:boolean){setBusy(true);try{const commit=()=>{const previous=readPilot(localStorage.getItem(PILOT_KEY));const next=[...previous,{id:crypto.randomUUID(),element,done,at:new Date().toISOString()}];localStorage.setItem(PILOT_KEY,JSON.stringify(next));setEvents(next);};if(navigator.locks)await navigator.locks.request(PILOT_KEY,commit);else commit();setError('');}catch(e){setError(e instanceof Error?e.message:'Registro não salvo.');}finally{setBusy(false);}}
 const start=tasks.map(t=>t.start).sort()[0]||'2026-10-05',finish=tasks.map(t=>t.end).sort().at(-1)||'2027-12-31';
 return <div className="client-shell"><header className="client-header"><Link className="brand" href="/demo">obra clara.</Link><Link href="/planejamento/demo">Planning</Link></header><main className="client-main planning-main"><section className="page-title"><div><span className="eyebrow">PRIMROSE · KITCHEN PILOT</span><h1>Veja a cozinha ganhar forma.</h1><p>Framing, instalações e acabamento vinculados às atividades do planejamento.</p></div><span className="small-chip">Protótipo local</span></section>
 <p className="planning-intro">Referência: planta A1.2 do PDF Primrose. Modelo esquemático com duas paredes e abertura sobre a pia. Pé-direito de 10 ft indicado na planta; largura de 14.54 ft e profundidade de 12 ft são aproximações para este teste. Trajetos de instalações são ilustrativos. Geometria não validada para quantitativos ou execução.</p>
 {error&&<p role="alert" className="alert error">{error}</p>}
 <div className="pilot-layout"><section className="panel pilot-visual"><div className="planning-tabs" aria-label="Modo de visualização"><button aria-pressed={mode==='actual'} className={mode==='actual'?'selected':''} onClick={()=>setMode('actual')}>Execução registrada</button><button aria-pressed={mode==='simulation'} className={mode==='simulation'?'selected':''} onClick={()=>setMode('simulation')}>Simular cronograma</button></div>
 {mode==='simulation'?<div className="pilot-controls"><label>Data da simulação<input type="date" value={date} min={start} max={finish} onChange={e=>setDate(e.target.value)}/></label><button className="button secondary" onClick={()=>setDate(finish)}>Ver final planejado</button><p>Uma camada aparece quando sua atividade vinculada termina. Simular não cria registros de execução.</p></div>:<p className="panel-note">{actual.size} de {elements.length} elementos do piloto registrados. Esta contagem não representa o avanço físico total da obra.</p>}
 <KitchenScene done={shown} xray={xray}/><label className="pilot-camera"><input type="checkbox" checked={xray} onChange={e=>setXray(e.target.checked)}/> Tornar drywall transparente para examinar as instalações</label><p className="panel-note">Madeira: framing · azul/vermelho: água · amarelo: elétrica · branco: drywall</p></section>
 <section className="panel pilot-records"><h2>Kitchen work packages</h2><p>Confirme somente o que foi executado. Para desfazer, desmarque o elemento; a correção permanece no histórico.</p>{elements.map(e=>{const task=tasks.find(t=>t.id===e.task);return <article key={e.id}><label><input type="checkbox" checked={actual.has(e.id)} disabled={!ready||busy||mode==='simulation'} onChange={v=>void record(e.id,v.target.checked)}/><strong>{e.name}</strong></label><small>{task?task.name+' · '+task.start+' → '+task.end:'Atividade não encontrada no planejamento'}</small><span>{shown.has(e.id)?mode==='actual'?'Registrado':'Visível na simulação':'Ainda não aparece'}</span></article>;})}<p className="panel-note">Os registros são exclusivos deste piloto e deste navegador. Ainda não alteram a EAP, os custos ou a página do cliente. Vínculos iniciais usam as atividades do modelo americano.</p></section></div>
 <section className="panel pilot-records"><h2>Histórico do piloto</h2>{events.length?<ul>{events.slice(-10).reverse().map(e=><li key={e.id}>{elements.find(x=>x.id===e.element)?.name} — {e.done?'Execução registrada':'Registro desfeito'} · {new Date(e.at).toLocaleString('pt-BR',{timeZone:'America/Denver'})} (Utah)</li>)}</ul>:<p>Nenhuma execução registrada. Experimente primeiro a simulação do cronograma.</p>}</section>
 </main></div>;
}
