"use client";
import {materialLocations} from '@/lib/material-locations';
import Link from 'next/link';import {useEffect,useState,type FormEvent} from 'react';import {listPurchases,listWithdrawals,saveWithdrawal,type Purchase} from '@/lib/material-purchases';import {availableMaterial,type Withdrawal} from '@/lib/material-withdrawals';import {readPlan,PLAN_KEY} from '@/lib/planning';
export function MaterialWithdrawals(){
 const [purchases,setPurchases]=useState<Purchase[]>([]),[rows,setRows]=useState<Withdrawal[]>([]),[phases,setPhases]=useState<string[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 async function refresh(){try{const [p,r]=await Promise.all([listPurchases(),listWithdrawals()]);setPurchases(p);setRows(r);setPhases(Array.from(new Set(readPlan(localStorage.getItem(PLAN_KEY)).tasks.map(t=>t.phase||'Other activities'))));setReady(true);}catch(e){setReady(false);setError(e instanceof Error?e.message:'Não foi possível abrir os materiais.');}}
 useEffect(()=>{void refresh();},[]);
 const material=purchases.find(p=>p.id===selected),received=purchases.filter(p=>p.status==='received');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!material)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{await saveWithdrawal({id:crypto.randomUUID(),purchaseId:material.id,material:material.name,unit:material.unit,quantity:Number(f.get('quantity')),date:String(f.get('date')),responsible:String(f.get('responsible')).trim(),phase:String(f.get('phase')),location:String(f.get('location')).trim(),note:String(f.get('note')).trim(),createdAt:''});await refresh();setRevision(v=>v+1);setNotice('Retirada registrada e saldo atualizado.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar.');await refresh();}finally{setBusy(false);}}
 const locations=materialLocations(purchases.map(p=>p.location),rows.map(r=>r.location));
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 return <div className="client-shell"><header className="client-header"><Link className="brand" href="/demo">obra clara.</Link><Link href="/materiais/demo">Materiais e compras</Link></header><main className="client-main planning-main"><section className="page-title"><div><span className="eyebrow">MATERIAL WITHDRAWALS</span><h1>Retirada de materiais</h1><p>Registre quem retirou, quanto e onde o material será utilizado.</p></div><button className="button secondary" disabled={busy} onClick={()=>void refresh()}>Atualizar saldos</button></section><p className="planning-intro">Controle local por item de compra recebido. Recebido representa a quantidade integral da compra; recebimentos parciais ainda não são suportados. Retirar não registra execução, pagamento ou custo adicional. Os dados ficam neste navegador.</p>{error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="alert success" role="status">{notice}</p>}
 <section className="panel purchase-editor"><h2>Nova retirada</h2><label>Material recebido<select value={selected} disabled={!ready||busy} onChange={e=>{setSelected(e.target.value);setNotice('');}}><option value="">Selecione um item de compra</option>{received.map(p=><option key={p.id} value={p.id}>{p.name} · {p.vendor||'Fornecedor não informado'} · {p.invoiceNumber||p.id.slice(0,8)} · saldo {availableMaterial(p,rows)} {p.unit}</option>)}</select></label>{ready&&!received.length&&<p>Nenhum material recebido. Marque a compra como Recebido na tela de materiais.</p>}{material&&<form key={selected+revision} onSubmit={submit}><fieldset disabled={busy}><p>Disponível: <strong>{availableMaterial(material,rows)} {material.unit}</strong> · origem: {material.phase} / {material.location}</p><div className="form-grid"><label>Quantidade retirada ({material.unit})<input name="quantity" type="number" min="0.001" max={availableMaterial(material,rows)} step="0.001" required/></label><label>Data da retirada<input name="date" type="date" required max={today} defaultValue={today}/></label><label>Responsável pela retirada<input name="responsible" maxLength={100} required/></label><label>Fase de destino<select name="phase" defaultValue={material.phase} required>{Array.from(new Set([...phases,material.phase])).map(p=><option key={p}>{p}</option>)}</select></label><label>Local de destino<select name="location" required defaultValue={material.location}>{locations.map(location=><option key={location} value={location}>{location}</option>)}</select></label><label>Observação<textarea name="note" maxLength={500}/></label></div><button className="button primary" disabled={!ready||availableMaterial(material,rows)<=0}>{busy?'Registrando…':'Registrar retirada'}</button></fieldset></form>}</section>
 <section className="panel purchase-editor"><h2>Saldo dos materiais recebidos</h2><div className="table-scroll"><table className="planning-table"><thead><tr>{['Material / compra','Recebido','Retirado','Disponível'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{received.map(p=><tr key={p.id}><td>{p.name}<div>{p.vendor} · {p.invoiceNumber||p.id.slice(0,8)}</div></td><td>{p.quantity} {p.unit}</td><td>{Number((p.quantity-availableMaterial(p,rows)).toFixed(3))} {p.unit}</td><td>{availableMaterial(p,rows)} {p.unit}</td></tr>)}</tbody></table></div></section>
 <section className="panel purchase-editor"><h2>Histórico de retiradas</h2><p>Registros preservados. Estorno e devolução ainda não disponíveis nesta primeira versão.</p><div className="table-scroll"><table className="planning-table"><thead><tr>{['Data','Material','Quantidade','Responsável','Fase / local','Observação'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{[...rows].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=><tr key={r.id}><td>{r.date}</td><td>{r.material}<div>Compra {r.purchaseId.slice(0,8)}</div></td><td>{r.quantity} {r.unit}</td><td>{r.responsible}</td><td>{r.phase}<div>{r.location}</div></td><td>{r.note||'—'}</td></tr>)}</tbody></table></div>{!rows.length&&<p>Nenhuma retirada registrada.</p>}</section></main></div>;
}
