"use client";
import {useState,type ChangeEvent} from 'react';
import {readMaterialWorkbook,type ImportRow} from '@/lib/material-import';
import {importPurchases,listPurchases} from '@/lib/material-purchases';
import {readPlan,PLAN_KEY} from '@/lib/planning';
export function MaterialImporter({onImported,disabled}:{onImported:()=>Promise<void>;disabled:boolean}){
 const [rows,setRows]=useState<ImportRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function select(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;setRows([]);setError('');setNotice('');setBusy(true);try{if(!file.name.toLowerCase().endsWith('.xlsx')||file.size>2*1024*1024)throw Error('Selecione um arquivo .xlsx de até 2 MB.');const phases=Array.from(new Set(readPlan(localStorage.getItem(PLAN_KEY)).tasks.map(t=>t.phase||'Other activities')));setRows(await readMaterialWorkbook(await file.arrayBuffer(),phases,await listPurchases()));}catch(e){setError(e instanceof Error?e.message:'Não foi possível ler o Excel.');}finally{setBusy(false);}}
 const valid=rows.filter(r=>!r.errors.length&&!r.duplicate),errors=rows.filter(r=>r.errors.length),duplicates=rows.filter(r=>r.duplicate);
 async function confirm(){if(busy||errors.length||!valid.length)return;setBusy(true);setError('');try{const phases=new Set(readPlan(localStorage.getItem(PLAN_KEY)).tasks.map(t=>t.phase||'Other activities'));if(valid.some(r=>!phases.has(r.item.phase)))throw Error('O planejamento mudou. Envie o arquivo novamente.');const count=await importPurchases(valid.map(r=>r.item));setRows([]);setNotice(count+' materiais importados. Itens idênticos já existentes foram ignorados. Anexe os comprovantes em Editar / anexar.');await onImported();}catch(e){setError(e instanceof Error?e.message:'Não foi possível importar.');}finally{setBusy(false);}}
 return <section className="panel purchase-editor"><h2>Importar materiais do Excel</h2><p>Baixe o modelo, preencha a aba Materials e envie para revisar. Até 500 itens por arquivo. O template contém as fases padrão americanas; fases personalizadas devem ter o mesmo nome do planejamento.</p><div className="planning-actions"><a className="button secondary" href="/templates/materials-template.xlsx" download>Baixar template Excel</a><label className="button secondary">{busy?'Processando…':'Selecionar Excel'}<input aria-label="Selecionar Excel" type="file" accept=".xlsx" disabled={busy||disabled} onChange={select}/></label></div>{error&&<p role="alert" className="alert error">{error}</p>}{notice&&<p role="status" className="alert success">{notice}</p>}
 {!!rows.length&&<div><h3>Revisão antes de importar</h3><p>{valid.length} novos · {errors.length} com erro · {duplicates.length} possíveis duplicados ignorados.</p><p>Itens com todos os campos iguais são ignorados, incluindo repetições no arquivo. Corrija os erros no Excel e envie novamente. Nenhum item foi salvo nesta revisão.</p><div className="table-scroll"><table className="planning-table"><thead><tr>{['Linha','Material','Quantidade','Fornecedor','Total USD','Data','Fase / local','Situação','Validação'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.item.name}</td><td>{Number.isFinite(r.item.quantity)?r.item.quantity:'—'} {r.item.unit}</td><td>{r.item.vendor}</td><td>{Number.isFinite(r.item.totalCents)?(r.item.totalCents/100).toFixed(2):'—'}</td><td>{r.item.date}</td><td>{r.item.phase}<div>{r.item.location}</div></td><td>{r.item.status}</td><td>{r.errors.length?r.errors.join(' '):r.duplicate?'Duplicado: será ignorado':'Pronto para importar'}</td></tr>)}</tbody></table></div><div className="planning-actions"><button className="button primary" disabled={busy||!!errors.length||!valid.length} onClick={confirm}>Confirmar importação de {valid.length} materiais</button><button className="button secondary" disabled={busy} onClick={()=>setRows([])}>Cancelar</button></div></div>}</section>;
}
