"use client";
import {PurchasePricing} from "./purchase-pricing";

import {MaterialImporter} from "./material-importer";
import {materialLocations} from "@/lib/material-locations";
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
import {PLAN_KEY,readPlan} from '@/lib/planning';
import {listPurchases,savePurchase,paymentLabel,calculatePurchaseTotal,inputCents,type Purchase} from '@/lib/material-purchases';
const statuses:Record<string,string>={planned:'A comprar',ordered:'Comprado / aguardando entrega',received:'Recebido'};
const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
export function MaterialPurchases(){
 const [items,setItems]=useState<Purchase[]>([]),[phases,setPhases]=useState<string[]>([]),[editing,setEditing]=useState<Purchase|null>(null),[formOpen,setFormOpen]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[filter,setFilter]=useState('all');
 useEffect(()=>{let active=true;async function load(){try{const plan=readPlan(localStorage.getItem(PLAN_KEY));const rows=await listPurchases();if(active){setItems(rows);setPhases(Array.from(new Set(plan.tasks.map(t=>t.phase||'Other activities'))));setReady(true);}}catch{if(active)setError('Não foi possível abrir os dados locais. Os registros existentes foram preservados.');}}void load();return()=>{active=false;};},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const file=f.get('receipt') as File;const item:Purchase={id:editing?.id??crypto.randomUUID(),name:String(f.get('name')).trim(),quantity:Number(f.get('quantity')),unit:String(f.get('unit')),unitCostCents:inputCents(String(f.get('unitCost'))),shippingCents:inputCents(String(f.get('shipping'))),totalCents:calculatePurchaseTotal(Number(f.get('quantity')),inputCents(String(f.get('unitCost'))),inputCents(String(f.get('tax'))),inputCents(String(f.get('shipping')))),vendor:String(f.get('vendor')),date:String(f.get('date')),phase:String(f.get('phase')),location:String(f.get('location')).trim(),status:String(f.get('status')),invoiceNumber:String(f.get('invoiceNumber')).trim(),dueDate:String(f.get('dueDate')),taxMode:f.get('taxMode')==='rate'?'rate':'manual',taxRate:f.get('taxMode')==='rate'?Number(f.get('taxRate')):undefined,shippingTaxable:f.get('taxMode')==='rate'?f.get('shippingTaxable')==='yes':undefined,taxCents:inputCents(String(f.get('tax'))),paidCents:String(f.get('paid')).trim()===''?undefined:Math.round(Number(f.get('paid'))*100),receipt:file?.size?file:editing?.receipt};await savePurchase(item);setItems(await listPurchases());setFormOpen(false);setEditing(null);setNotice('Material salvo com fase, local e comprovante neste navegador.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 function download(item:Purchase){if(!item.receipt)return;const url=URL.createObjectURL(item.receipt),a=document.createElement('a');a.href=url;a.download=item.receipt.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const locations=materialLocations(items.map(i=>i.location));
 return <div className="client-shell"><header className="client-header"><Link className="brand" href="/demo">obra clara.</Link><Link href="/materiais/retiradas">Retirada de materiais</Link><Link href="/planejamento/demo">Voltar ao planejamento</Link></header><main className="client-main planning-main"><section className="page-title"><div><span className="eyebrow">MATERIAL PURCHASES</span><h1>Materiais e compras</h1><p>Acompanhe cada compra, o destino na obra e seu comprovante.</p></div><button className="button primary" disabled={!ready||busy} onClick={()=>{setEditing(null);setFormOpen(true);setError('');}}>Adicionar material</button></section>
 <p className="planning-intro">Demonstração local em USD. Registros e comprovantes ficam somente neste navegador; não são compartilhados nem geram lançamentos financeiros. Limpar os dados do navegador remove esses registros. Os materiais planejados na EAP ainda não são importados automaticamente.</p>
 {error&&<p role="alert" className="alert error">{error}</p>}{notice&&<p role="status" className="alert success">{notice}</p>}
 <p className="planning-intro">Preparação financeira: dados por item para conferência. Recebimento e pagamento são independentes. Ainda não há exportação contábil ou conexão com QuickBooks/NetSuite. O Excel atual importa o total informado, sem preço unitário, shipping, fatura, vencimento, impostos ou pagamento; complete-os em Editar / anexar.</p>
 <MaterialImporter disabled={!ready||busy} onImported={async()=>setItems(await listPurchases())}/>
 <section className="client-facts"><article><div><span>Itens cadastrados</span><strong>{items.length}</strong></div></article><article><div><span>Compras registradas</span><strong>{usd(items.filter(i=>i.status!=='planned').reduce((s,i)=>s+i.totalCents,0))}</strong></div></article><article><div><span>Aguardando entrega</span><strong>{items.filter(i=>i.status==='ordered').length}</strong></div></article></section>
 {formOpen&&<section className="panel purchase-editor"><h2>{editing?'Editar material':'Novo material'}</h2><form key={editing?.id??'new'} onSubmit={submit}><fieldset disabled={busy}><div className="form-grid"><label>Material<input name="name" required maxLength={100} defaultValue={editing?.name} autoFocus/></label><label>Fornecedor<input name="vendor" maxLength={100} defaultValue={editing?.vendor}/></label><PurchasePricing item={editing}/><label>Unidade<input name="unit" required maxLength={25} defaultValue={editing?.unit??'each'}/></label><label>Data da compra<input name="date" type="date" defaultValue={editing?.date}/></label><label>Situação<select name="status" defaultValue={editing?.status??'planned'}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Fase da obra<select name="phase" required defaultValue={editing?.phase??''}><option value="" disabled>Selecione a fase</option>{Array.from(new Set([...phases,...items.map(i=>i.phase)])).map(p=><option key={p}>{p}</option>)}</select></label><label>Local de uso<input name="location" list="purchase-locations" required maxLength={100} placeholder="Selecione ou informe outro local" defaultValue={editing?.location}/><datalist id="purchase-locations">{locations.map(l=><option key={l} value={l}/>)}</datalist></label><label>Número da fatura<input name="invoiceNumber" maxLength={100} defaultValue={editing?.invoiceNumber}/></label><label>Vencimento<input name="dueDate" type="date" defaultValue={editing?.dueDate}/></label><label>Valor já pago deste item (USD)<input name="paid" type="number" min="0" step="0.01" defaultValue={editing?.paidCents===undefined?'':editing.paidCents/100}/><small>Pagamento independe do recebimento. Não repita aqui o total de uma fatura com vários itens.</small></label><label>Comprovante da compra<input name="receipt" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"/><small>PDF, JPG, PNG ou WebP · até 10 MB. {editing?.receipt?'Atual: '+editing.receipt.name+'. Um novo arquivo substitui o anterior.':''}</small></label></div><div className="planning-actions"><button className="button primary">{busy?'Salvando…':'Salvar material'}</button><button type="button" className="button secondary" onClick={()=>setFormOpen(false)}>Cancelar</button></div></fieldset></form></section>}
 <section className="panel"><div className="panel-heading"><h2>Lista de materiais</h2><label>Situação <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className="table-scroll"><table className="planning-table"><thead><tr>{['Material / fornecedor','Quantidade','Valor total','Situação / data','Fatura / vencimento','Pagamento','Fase','Local','Comprovante','Ações'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.filter(i=>filter==='all'||i.status===filter).map(i=><tr key={i.id}><td><strong>{i.name}</strong><div>{i.vendor||'Fornecedor a definir'}</div></td><td>{i.quantity} {i.unit}</td><td>{usd(i.totalCents)}<div>Unitário: {i.unitCostCents===undefined?'Não informado':usd(i.unitCostCents)}</div><div>Shipping: {i.shippingCents===undefined?'Não informado':usd(i.shippingCents)}</div><div>Impostos: {i.taxCents===undefined?'Não informados':usd(i.taxCents)}{i.taxMode==='rate'&&<small> · {i.taxRate}% informado · shipping {i.shippingTaxable?'tributável':'fora da base'}</small>}</div></td><td>{statuses[i.status]}<div>{i.date||'Sem data'}</div></td><td>{i.invoiceNumber||'Sem número'}<div>{i.dueDate||'Sem vencimento'}</div></td><td>{paymentLabel(i)}{i.paidCents!==undefined&&<div>Pago: {usd(i.paidCents)} · Restante: {usd(i.totalCents-i.paidCents)}</div>}</td><td>{i.phase}</td><td>{i.location}</td><td>{i.receipt?<button className="text-button" onClick={()=>download(i)}>Baixar {i.receipt.name}</button>:'Não anexado'}</td><td><button className="text-button" disabled={busy} onClick={()=>{setEditing(i);setFormOpen(true);setError('');}}>Editar / anexar</button></td></tr>)}</tbody></table></div>{ready&&!items.some(i=>filter==='all'||i.status===filter)&&<p className="planning-intro">Nenhum material nesta lista. Cadastre uma compra para começar.</p>}</section></main></div>;
}
