"use client";
import {useState} from 'react';import {calculatePurchaseTotal,calculateSalesTax,inputCents,type Purchase} from '@/lib/material-purchases';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
export function PurchasePricing({item}:{item:Purchase|null}){
 const [quantity,setQuantity]=useState(String(item?.quantity??1)),[unit,setUnit]=useState(item?.unitCostCents===undefined?'':String(item.unitCostCents/100)),[tax,setTax]=useState(String((item?.taxCents??0)/100)),[shipping,setShipping]=useState(String((item?.shippingCents??0)/100));
 const [mode,setMode]=useState(item?.taxMode??'manual'),[rate,setRate]=useState(item?.taxRate===undefined?'':String(item.taxRate)),[shippingTaxable,setShippingTaxable]=useState(item?.shippingTaxable??false);
 let computedTax:number|undefined;try{if(mode==='rate'&&rate.trim()!=='')computedTax=calculateSalesTax(calculatePurchaseTotal(Number(quantity),inputCents(unit),0,0),inputCents(shipping),Number(rate),shippingTaxable);}catch{}
 const appliedTax=mode==='manual'?tax:computedTax===undefined?'':(computedTax/100).toFixed(2);
 let total:number|undefined,subtotal:number|undefined;try{total=calculatePurchaseTotal(Number(quantity),inputCents(unit),inputCents(appliedTax),inputCents(shipping));subtotal=calculatePurchaseTotal(Number(quantity),inputCents(unit),0,0);}catch{}
 return <><label>Quantidade<input name="quantity" type="number" min="0.001" max="1000000000" step="0.001" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Valor unitário (USD)<input name="unitCost" type="number" min="0" step="0.01" required value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Como informar o imposto<select name="taxMode" value={mode} onChange={e=>setMode(e.target.value as 'manual'|'rate')}><option value="manual">Valor da fatura (USD)</option><option value="rate">Calcular por Sales tax (%)</option></select></label>{mode==='rate'&&<><label>Sales tax (%)<input name="taxRate" type="number" min="0" max="100" step="0.0001" required value={rate} onChange={e=>setRate(e.target.value)}/><small>Alíquota informada por você. Sem consulta automática ao IRS ou ao estado.</small></label><label>Shipping integra a base tributável?<select name="shippingTaxable" value={shippingTaxable?'yes':'no'} onChange={e=>setShippingTaxable(e.target.value==='yes')}><option value="no">Não incluir shipping</option><option value="yes">Incluir shipping</option></select><small>Confirme conforme a transação; o portal não determina a regra fiscal.</small></label></>}<label>Impostos deste item (USD)<input name="tax" type="number" min="0" step="0.01" required value={appliedTax} readOnly={mode==='rate'} onChange={e=>setTax(e.target.value)}/><small>{mode==='rate'?'Estimativa calculada sobre o subtotal e o shipping quando selecionado.':'Valor em dólares da fatura. Informe zero quando não houver.'}</small></label><label>Shipping / frete deste item (USD)<input name="shipping" type="number" min="0" step="0.01" required value={shipping} onChange={e=>setShipping(e.target.value)}/><small>Informe apenas o frete atribuído a este item para evitar duplicação.</small></label><div className="planning-intro" aria-live="polite"><div>Subtotal: {subtotal===undefined?'—':money(subtotal)}</div><strong>Total calculado: {total===undefined?'Preencha os valores':money(total)}</strong><div>Quantidade × valor unitário + impostos + shipping</div>{item?.unitCostCents===undefined&&item&&<small>Registro anterior: {money(item.totalCents)}. Informe o preço unitário e confira impostos/frete antes de salvar; o total anterior não foi convertido automaticamente.</small>}</div></>;
}
